spring.profiles.active: development
logging.level.org.springframework.cloud.kubernetes: DEBUG
message: hello default
management.server.port: 8081
server:
  port: 3002
---
spring.profiles: development
message: hello development
---
spring.profiles: kubernetes
message: hello kubernetes
